services:
  web-admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDER_STAGE: builder-staging  # Use staging build configuration
    container_name: web-admin-staging
    networks:
      - proxy
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"] 
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  proxy:
    external: true
